### ISSUE TITLE
Cypress exception during test run

### ISSUE THREAD

**Issue by shauvik** [cypress-io/cypress-cli#11]
This is a hard to reproduce error but cypress crashed while running the test once in the CI environment. So, I wanted to send you the stack trace so you know about the issue and can address it in a future release.

```
Error processing argument at index 0, conversion failure from null
TypeError: Error processing argument at index 0, conversion failure from null
  at TypeError (native)
  at exit (/root/.cypress/Cypress/resources/app/index.js:1734:20)
  at tryCatcher (/root/.cypress/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/root/.cypress/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:503:31)
  at Promise._settlePromise (/root/.cypress/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:560:18)
  at Promise._settlePromise0 (/root/.cypress/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:605:10)
  at Promise._settlePromises (/root/.cypress/Cypress/resources/app/node_modules/bluebird/js/release/promise.js:684:18)
  at Async._drainQueue (/root/.cypress/Cypress/resources/app/node_modules/bluebird/js/release/async.js:126:16)
  at Async._drainQueues (/root/.cypress/Cypress/resources/app/node_modules/bluebird/js/release/async.js:136:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/root/.cypress/Cypress/resources/app/node_modules/bluebird/js/release/async.js:16:14)
  at tryOnImmediate (timers.js:534:15)
  at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by brian-mann** [comment]
What version of cypress are you running?

**Comment by shauvik** [comment]
Yes, you are right. Our docker container is still running 0.16.2 I will update it. Thanks!
